Creating keycloak ... 
[1A[2KCreating keycloak ... [32mdone[0m[1BAttaching to keycloak
[36mkeycloak        |[0m Updating the configuration and installing your custom providers, if any. Please wait.
[36mkeycloak        |[0m 2023-05-02 10:17:14,035 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 20786ms
[36mkeycloak        |[0m 2023-05-02 10:17:16,542 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: https://www.d-defrance.fr/keycloak, Hostname: www.d-defrance.fr, Strict HTTPS: true, Path: /keycloak, Strict BackChannel: false, Admin URL: https://www.d-defrance.fr/keycloak, Admin: www.d-defrance.fr, Port: -1, Proxied: true
[36mkeycloak        |[0m 2023-05-02 10:17:18,972 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
[36mkeycloak        |[0m 2023-05-02 10:17:20,505 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
[36mkeycloak        |[0m 2023-05-02 10:17:20,525 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
[36mkeycloak        |[0m 2023-05-02 10:17:20,624 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
[36mkeycloak        |[0m 2023-05-02 10:17:21,354 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.10.Final
[36mkeycloak        |[0m 2023-05-02 10:17:21,600 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
[36mkeycloak        |[0m 2023-05-02 10:17:22,204 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_574231, Site name: null
[36mkeycloak        |[0m 2023-05-02 10:17:23,530 INFO  [io.quarkus] (main) Keycloak 20.0.3 on JVM (powered by Quarkus 2.13.6.Final) started in 9.356s. Listening on: http://0.0.0.0:8989
[36mkeycloak        |[0m 2023-05-02 10:17:23,538 INFO  [io.quarkus] (main) Profile dev activated. 
[36mkeycloak        |[0m 2023-05-02 10:17:23,539 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
[36mkeycloak        |[0m 2023-05-02 10:17:23,607 ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists
[36mkeycloak        |[0m 2023-05-02 10:17:23,610 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
[36mkeycloak        |[0m 2023-05-02 11:39:46,504 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-38) SQL Error: 23505, SQLState: 23505
[36mkeycloak        |[0m 2023-05-02 11:39:46,506 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-38) Unique index or primary key violation: "PUBLIC.UK_ORVSDMLA56612EAEFIQ6WL5OI_INDEX_6 ON PUBLIC.REALM(NAME NULLS FIRST) VALUES ( /* 5 */ 'myrealm' )"; SQL statement:
[36mkeycloak        |[0m insert into REALM (ACCESS_CODE_LIFESPAN, LOGIN_LIFESPAN, USER_ACTION_LIFESPAN, ACCESS_TOKEN_LIFESPAN, ACCESS_TOKEN_LIFE_IMPLICIT, ACCOUNT_THEME, ADMIN_EVENTS_DETAILS_ENABLED, ADMIN_EVENTS_ENABLED, ADMIN_THEME, ALLOW_USER_MANAGED_ACCESS, BROWSER_FLOW, CLIENT_AUTH_FLOW, DEFAULT_LOCALE, DEFAULT_ROLE, DIRECT_GRANT_FLOW, DOCKER_AUTH_FLOW, DUPLICATE_EMAILS_ALLOWED, EDIT_USERNAME_ALLOWED, EMAIL_THEME, ENABLED, EVENTS_ENABLED, EVENTS_EXPIRATION, INTERNATIONALIZATION_ENABLED, LOGIN_THEME, LOGIN_WITH_EMAIL_ALLOWED, MASTER_ADMIN_CLIENT, NAME, NOT_BEFORE, OFFLINE_SESSION_IDLE_TIMEOUT, OTP_POLICY_ALG, OTP_POLICY_DIGITS, OTP_POLICY_COUNTER, OTP_POLICY_WINDOW, OTP_POLICY_PERIOD, OTP_POLICY_TYPE, PASSWORD_POLICY, REFRESH_TOKEN_MAX_REUSE, REGISTRATION_ALLOWED, REG_EMAIL_AS_USERNAME, REGISTRATION_FLOW, REMEMBER_ME, RESET_CREDENTIALS_FLOW, RESET_PASSWORD_ALLOWED, REVOKE_REFRESH_TOKEN, SSL_REQUIRED, SSO_IDLE_TIMEOUT, SSO_IDLE_TIMEOUT_REMEMBER_ME, SSO_MAX_LIFESPAN, SSO_MAX_LIFESPAN_REMEMBER_ME, VERIFY_EMAIL, ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]
[36mkeycloak        |[0m 2023-05-02 11:39:46,512 INFO  [org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl] (executor-thread-38) HHH000010: On release of batch it still contained JDBC statements
[36mkeycloak        |[0m 2023-05-02 11:39:46,515 ERROR [org.keycloak.services.resources.admin.RealmsAdminResource] (executor-thread-38) Conflict detected: org.keycloak.models.ModelDuplicateException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
[36mkeycloak        |[0m 	at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:80)
[36mkeycloak        |[0m 	at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:62)
[36mkeycloak        |[0m 	at com.sun.proxy.$Proxy74.flush(Unknown Source)
[36mkeycloak        |[0m 	at org.keycloak.models.jpa.JpaRealmProvider.createRealm(JpaRealmProvider.java:111)
[36mkeycloak        |[0m 	at org.keycloak.models.cache.infinispan.RealmCacheSession.createRealm(RealmCacheSession.java:401)
[36mkeycloak        |[0m 	at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:518)
[36mkeycloak        |[0m 	at org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:503)
[36mkeycloak        |[0m 	at org.keycloak.services.managers.RealmManagerProviderFactory.lambda$postInit$0(RealmManagerProviderFactory.java:51)
[36mkeycloak        |[0m 	at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:92)
[36mkeycloak        |[0m 	at org.keycloak.storage.ImportRealmFromRepresentation.fire(ImportRealmFromRepresentation.java:50)
[36mkeycloak        |[0m 	at org.keycloak.storage.datastore.LegacyExportImportManager.importRealm(LegacyExportImportManager.java:155)
[36mkeycloak        |[0m 	at org.keycloak.services.resources.admin.RealmsAdminResource.importRealm(RealmsAdminResource.java:133)
[36mkeycloak        |[0m 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[36mkeycloak        |[0m 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[36mkeycloak        |[0m 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[36mkeycloak        |[0m 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
[36mkeycloak        |[0m 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
[36mkeycloak        |[0m 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
[36mkeycloak        |[0m 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
[36mkeycloak        |[0m 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
[36mkeycloak        |[0m 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
[36mkeycloak        |[0m 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
[36mkeycloak        |[0m 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
[36mkeycloak        |[0m 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
[36mkeycloak        |[0m 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
[36mkeycloak        |[0m 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
[36mkeycloak        |[0m 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
[36mkeycloak        |[0m 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
[36mkeycloak        |[0m 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
[36mkeycloak        |[0m 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
[36mkeycloak        |[0m 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
[36mkeycloak        |[0m 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
[36mkeycloak        |[0m 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
[36mkeycloak        |[0m 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
[36mkeycloak        |[0m 	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
[36mkeycloak        |[0m 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
[36mkeycloak        |[0m 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[36mkeycloak        |[0m 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[36mkeycloak        |[0m 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
[36mkeycloak        |[0m 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
[36mkeycloak        |[0m 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[36mkeycloak        |[0m 	at java.base/java.lang.Thread.run(Thread.java:829)
[36mkeycloak        |[0m Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
[36mkeycloak        |[0m 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
[36mkeycloak        |[0m 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
[36mkeycloak        |[0m 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
[36mkeycloak        |[0m 	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1411)
[36mkeycloak        |[0m 	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1394)
[36mkeycloak        |[0m 	at jdk.internal.reflect.GeneratedMethodAccessor228.invoke(Unknown Source)
[36mkeycloak        |[0m 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[36mkeycloak        |[0m 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[36mkeycloak        |[0m 	at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:60)
[36mkeycloak        |[0m 	... 56 more
[36mkeycloak        |[0m Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
[36mkeycloak        |[0m 	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59)
[36mkeycloak        |[0m 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
[36mkeycloak        |[0m 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
[36mkeycloak        |[0m 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
[36mkeycloak        |[0m 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
[36mkeycloak        |[0m 	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46)
[36mkeycloak        |[0m 	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3375)
[36mkeycloak        |[0m 	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3937)
[36mkeycloak        |[0m 	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107)
[36mkeycloak        |[0m 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
[36mkeycloak        |[0m 	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
[36mkeycloak        |[0m 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
[36mkeycloak        |[0m 	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
[36mkeycloak        |[0m 	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344)
[36mkeycloak        |[0m 	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
[36mkeycloak        |[0m 	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
[36mkeycloak        |[0m 	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407)
[36mkeycloak        |[0m 	... 61 more
[36mkeycloak        |[0m Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.UK_ORVSDMLA56612EAEFIQ6WL5OI_INDEX_6 ON PUBLIC.REALM(NAME NULLS FIRST) VALUES ( /* 5 */ 'myrealm' )"; SQL statement:
[36mkeycloak        |[0m insert into REALM (ACCESS_CODE_LIFESPAN, LOGIN_LIFESPAN, USER_ACTION_LIFESPAN, ACCESS_TOKEN_LIFESPAN, ACCESS_TOKEN_LIFE_IMPLICIT, ACCOUNT_THEME, ADMIN_EVENTS_DETAILS_ENABLED, ADMIN_EVENTS_ENABLED, ADMIN_THEME, ALLOW_USER_MANAGED_ACCESS, BROWSER_FLOW, CLIENT_AUTH_FLOW, DEFAULT_LOCALE, DEFAULT_ROLE, DIRECT_GRANT_FLOW, DOCKER_AUTH_FLOW, DUPLICATE_EMAILS_ALLOWED, EDIT_USERNAME_ALLOWED, EMAIL_THEME, ENABLED, EVENTS_ENABLED, EVENTS_EXPIRATION, INTERNATIONALIZATION_ENABLED, LOGIN_THEME, LOGIN_WITH_EMAIL_ALLOWED, MASTER_ADMIN_CLIENT, NAME, NOT_BEFORE, OFFLINE_SESSION_IDLE_TIMEOUT, OTP_POLICY_ALG, OTP_POLICY_DIGITS, OTP_POLICY_COUNTER, OTP_POLICY_WINDOW, OTP_POLICY_PERIOD, OTP_POLICY_TYPE, PASSWORD_POLICY, REFRESH_TOKEN_MAX_REUSE, REGISTRATION_ALLOWED, REG_EMAIL_AS_USERNAME, REGISTRATION_FLOW, REMEMBER_ME, RESET_CREDENTIALS_FLOW, RESET_PASSWORD_ALLOWED, REVOKE_REFRESH_TOKEN, SSL_REQUIRED, SSO_IDLE_TIMEOUT, SSO_IDLE_TIMEOUT_REMEMBER_ME, SSO_MAX_LIFESPAN, SSO_MAX_LIFESPAN_REMEMBER_ME, VERIFY_EMAIL, ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-214]
[36mkeycloak        |[0m 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
[36mkeycloak        |[0m 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
[36mkeycloak        |[0m 	at org.h2.message.DbException.get(DbException.java:223)
[36mkeycloak        |[0m 	at org.h2.message.DbException.get(DbException.java:199)
[36mkeycloak        |[0m 	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
[36mkeycloak        |[0m 	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
[36mkeycloak        |[0m 	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
[36mkeycloak        |[0m 	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
[36mkeycloak        |[0m 	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
[36mkeycloak        |[0m 	at org.h2.command.dml.Insert.update(Insert.java:135)
[36mkeycloak        |[0m 	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
[36mkeycloak        |[0m 	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
[36mkeycloak        |[0m 	at org.h2.command.Command.executeUpdate(Command.java:252)
[36mkeycloak        |[0m 	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
[36mkeycloak        |[0m 	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
[36mkeycloak        |[0m 	at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
[36mkeycloak        |[0m 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
[36mkeycloak        |[0m 	... 73 more
[36mkeycloak        |[0m 
Exception in thread Thread-3:
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 380, in _make_request
  File "http/client.py", line 1331, in getresponse
  File "http/client.py", line 297, in begin
  File "http/client.py", line 258, in _read_status
  File "socket.py", line 586, in readinto
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 638, in urlopen
  File "site-packages/urllib3/util/retry.py", line 368, in increment
  File "site-packages/urllib3/packages/six.py", line 685, in reraise
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 380, in _make_request
  File "http/client.py", line 1331, in getresponse
  File "http/client.py", line 297, in begin
  File "http/client.py", line 258, in _read_status
  File "socket.py", line 586, in readinto
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "compose/cli/log_printer.py", line 166, in tail_container_logs
  File "compose/cli/log_printer.py", line 197, in wait_on_exit
  File "compose/container.py", line 281, in wait
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1285, in wait
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 226, in _post
  File "site-packages/requests/sessions.py", line 572, in post
  File "site-packages/requests/sessions.py", line 524, in request
  File "site-packages/requests/sessions.py", line 637, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Exception in thread Thread-4:
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 380, in _make_request
  File "http/client.py", line 1331, in getresponse
  File "http/client.py", line 297, in begin
  File "http/client.py", line 258, in _read_status
  File "socket.py", line 586, in readinto
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 638, in urlopen
  File "site-packages/urllib3/util/retry.py", line 368, in increment
  File "site-packages/urllib3/packages/six.py", line 685, in reraise
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 380, in _make_request
  File "http/client.py", line 1331, in getresponse
  File "http/client.py", line 297, in begin
  File "http/client.py", line 258, in _read_status
  File "socket.py", line 586, in readinto
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "compose/cli/log_printer.py", line 214, in watch_events
  File "compose/project.py", line 493, in yield_loop
  File "compose/project.py", line 461, in build_container_event
  File "compose/container.py", line 48, in from_id
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 755, in inspect_container
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 230, in _get
  File "site-packages/requests/sessions.py", line 537, in get
  File "site-packages/requests/sessions.py", line 524, in request
  File "site-packages/requests/sessions.py", line 637, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Gracefully stopping... (press Ctrl+C again to force)
